app:
  scheduler:
    enable: true
    interval: PT10S
    force-check-delay: PT10S
  database-access-type: jpa
  retry:
    retryType: EXPONENTIAL
    statuses: [500, 501, 502, 503, 504, 505, 506, 507, 508, 509, 510, 520]
    attempts: 3
    delay: 2000
spring:
  liquibase:
    enabled: false
  application:
    name: scrapper
  datasource:
    url: jdbc:postgresql://localhost:5437/scrapper
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        show_sql: true
        format_sql: true
server:
  port: 8080

logging:
  config: classpath:log4j2-plain.xml
springdoc:
  swagger-ui:
    path: /swagger-ui
