app:
  telegram-token: ${TOKEN}
  retry:
    retryType: EXPONENTIAL
    statuses: [500, 501, 502, 503, 504, 505, 506, 507, 508, 509, 510, 520]
    attempts: 3
    delay: 2000
  kafka:
    bootstrap-servers: localhost:9092
    topicName: "updatesForBot"
    consumer:
      group-id: "botMessages"
    error-topic-name: errorBotMessages_dlq
spring:
  application:
    name: bot
  jackson:
    time-zone: UTC

server:
  port: 8090

logging:
  config: classpath:log4j2-plain.xml
springdoc:
  swagger-ui:
    path: /swagger-ui
management:
  server:
    port: 8091
  endpoints:
    web:
      base-path: "/"
      path-mapping:
        prometheus: "metrics"
      exposure:
        include: info, health, prometheus
  endpoint:
    info:
      enabled: true
    health:
      enabled: true
    prometheus:
      enabled: true
  prometheus:
    metrics:
      export:
        enabled: true
  metrics:
    tags:
      application: ${spring.application.name}
    distribution:
      percentiles-histogram:
        "[http.server.requests]": true
