/*
 * This file is generated by jOOQ.
 */

package edu.java.repository.jooq.generation.tables.pojos;


import jakarta.validation.constraints.Size;
import java.beans.ConstructorProperties;
import java.io.Serializable;
import java.time.OffsetDateTime;
import javax.annotation.processing.Generated;
import org.jetbrains.annotations.Nullable;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "https://www.jooq.org",
        "jOOQ version:3.18.9"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class Link implements Serializable {

    private static final long serialVersionUID = 1L;

    private Long linkId;
    private String linkName;
    private OffsetDateTime lastCheck;
    private OffsetDateTime lastUpdate;
    private OffsetDateTime lastCommit;
    private Integer amountIssues;
    private String type;

    public Link() {}

    public Link(Link value) {
        this.linkId = value.linkId;
        this.linkName = value.linkName;
        this.lastCheck = value.lastCheck;
        this.lastUpdate = value.lastUpdate;
        this.lastCommit = value.lastCommit;
        this.amountIssues = value.amountIssues;
        this.type = value.type;
    }

    @ConstructorProperties({ "linkId", "linkName", "lastCheck", "lastUpdate", "lastCommit", "amountIssues", "type" })
    public Link(
        @Nullable Long linkId,
        @Nullable String linkName,
        @Nullable OffsetDateTime lastCheck,
        @Nullable OffsetDateTime lastUpdate,
        @Nullable OffsetDateTime lastCommit,
        @Nullable Integer amountIssues,
        @Nullable String type
    ) {
        this.linkId = linkId;
        this.linkName = linkName;
        this.lastCheck = lastCheck;
        this.lastUpdate = lastUpdate;
        this.lastCommit = lastCommit;
        this.amountIssues = amountIssues;
        this.type = type;
    }

    /**
     * Getter for <code>LINK.LINK_ID</code>.
     */
    @Nullable
    public Long getLinkId() {
        return this.linkId;
    }

    /**
     * Setter for <code>LINK.LINK_ID</code>.
     */
    public void setLinkId(@Nullable Long linkId) {
        this.linkId = linkId;
    }

    /**
     * Getter for <code>LINK.LINK_NAME</code>.
     */
    @Size(max = 511)
    @Nullable
    public String getLinkName() {
        return this.linkName;
    }

    /**
     * Setter for <code>LINK.LINK_NAME</code>.
     */
    public void setLinkName(@Nullable String linkName) {
        this.linkName = linkName;
    }

    /**
     * Getter for <code>LINK.LAST_CHECK</code>.
     */
    @Nullable
    public OffsetDateTime getLastCheck() {
        return this.lastCheck;
    }

    /**
     * Setter for <code>LINK.LAST_CHECK</code>.
     */
    public void setLastCheck(@Nullable OffsetDateTime lastCheck) {
        this.lastCheck = lastCheck;
    }

    /**
     * Getter for <code>LINK.LAST_UPDATE</code>.
     */
    @Nullable
    public OffsetDateTime getLastUpdate() {
        return this.lastUpdate;
    }

    /**
     * Setter for <code>LINK.LAST_UPDATE</code>.
     */
    public void setLastUpdate(@Nullable OffsetDateTime lastUpdate) {
        this.lastUpdate = lastUpdate;
    }

    /**
     * Getter for <code>LINK.LAST_COMMIT</code>.
     */
    @Nullable
    public OffsetDateTime getLastCommit() {
        return this.lastCommit;
    }

    /**
     * Setter for <code>LINK.LAST_COMMIT</code>.
     */
    public void setLastCommit(@Nullable OffsetDateTime lastCommit) {
        this.lastCommit = lastCommit;
    }

    /**
     * Getter for <code>LINK.AMOUNT_ISSUES</code>.
     */
    @Nullable
    public Integer getAmountIssues() {
        return this.amountIssues;
    }

    /**
     * Setter for <code>LINK.AMOUNT_ISSUES</code>.
     */
    public void setAmountIssues(@Nullable Integer amountIssues) {
        this.amountIssues = amountIssues;
    }

    /**
     * Getter for <code>LINK.TYPE</code>.
     */
    @Size(max = 31)
    @Nullable
    public String getType() {
        return this.type;
    }

    /**
     * Setter for <code>LINK.TYPE</code>.
     */
    public void setType(@Nullable String type) {
        this.type = type;
    }

    @Override
    public boolean equals(Object obj) {
        if (this == obj)
            return true;
        if (obj == null)
            return false;
        if (getClass() != obj.getClass())
            return false;
        final Link other = (Link) obj;
        if (this.linkId == null) {
            if (other.linkId != null)
                return false;
        }
        else if (!this.linkId.equals(other.linkId))
            return false;
        if (this.linkName == null) {
            if (other.linkName != null)
                return false;
        }
        else if (!this.linkName.equals(other.linkName))
            return false;
        if (this.lastCheck == null) {
            if (other.lastCheck != null)
                return false;
        }
        else if (!this.lastCheck.equals(other.lastCheck))
            return false;
        if (this.lastUpdate == null) {
            if (other.lastUpdate != null)
                return false;
        }
        else if (!this.lastUpdate.equals(other.lastUpdate))
            return false;
        if (this.lastCommit == null) {
            if (other.lastCommit != null)
                return false;
        }
        else if (!this.lastCommit.equals(other.lastCommit))
            return false;
        if (this.amountIssues == null) {
            if (other.amountIssues != null)
                return false;
        }
        else if (!this.amountIssues.equals(other.amountIssues))
            return false;
        if (this.type == null) {
            if (other.type != null)
                return false;
        }
        else if (!this.type.equals(other.type))
            return false;
        return true;
    }

    @Override
    public int hashCode() {
        final int prime = 31;
        int result = 1;
        result = prime * result + ((this.linkId == null) ? 0 : this.linkId.hashCode());
        result = prime * result + ((this.linkName == null) ? 0 : this.linkName.hashCode());
        result = prime * result + ((this.lastCheck == null) ? 0 : this.lastCheck.hashCode());
        result = prime * result + ((this.lastUpdate == null) ? 0 : this.lastUpdate.hashCode());
        result = prime * result + ((this.lastCommit == null) ? 0 : this.lastCommit.hashCode());
        result = prime * result + ((this.amountIssues == null) ? 0 : this.amountIssues.hashCode());
        result = prime * result + ((this.type == null) ? 0 : this.type.hashCode());
        return result;
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder("Link (");

        sb.append(linkId);
        sb.append(", ").append(linkName);
        sb.append(", ").append(lastCheck);
        sb.append(", ").append(lastUpdate);
        sb.append(", ").append(lastCommit);
        sb.append(", ").append(amountIssues);
        sb.append(", ").append(type);

        sb.append(")");
        return sb.toString();
    }
}
